

/*
============================================
; Title: Assignment 5.1
; Author: Becca Buechle
; Date: 15 March 2020
; Modified By:
; Description: Practice with keyed collection array.
;===========================================
*/

let sixFlags = new Map();

sixFlags.set["Roller Coaster", 40];
sixFlags.set("Carousel" 3);
SixFlags.set("Water Rides", 25);
sixFlags.set("Kiddy Rides", 15);

for (let[key, value] of sixFlags) {
    console.log(key + " : " + value);
}
