/*
============================================
; Title: Assignment 4.1
; Author: Becca Buechle
; Date: 06 March 2020
; Modified By:
; Description: Array Practice
;===========================================
*/

//array of video games
var videoGames = ["Oxygen Not Included", "World of Warcraft", "RimWorld", "Planet Zoo"];
var myFavoriteGame = videoGames[0];

//adding two video games to array
videoGames[3] = "Warcraft 3";
videoGames[4] = "Diablo 3";

//calling my favorite game
myFavoriteGame;
