/*
============================================
; Title: Assignment 6.3
; Author: Becca Buechle
; Date: 23 March 2020
; Modified By:
; Description: Object literals practice
;===========================================
*/

//header for assignment information
const header = require('../buechle-header.js');
console.log (header.display("Rebecca", "Buechle", "6.3_object_Literals"));
console.log("\n")

//object with properties and strings
var ticketSystem = {
  id: 404,
  name: "Geek Squad Tech Support",
  requestor: "Jack Bradshaw",
};
//calling object
ticketSystem;

