

/*============================================

; Title: Assignment 1.4

; Author: Joanna Brumfield

; Date: 15 February 2020

; Modified By: Becca Buechle

; Description: This program demonstrates the

; use of JavaScript variables and the

; console.log function for debugging using http://Node.js

===========================================*/

var firstName = 'Joanna';

var lastName = 'Brumfield';

var age = 32;

var street = 'some random street address';

var city = 'some random city name';

var zipCode = 'some random zip code';

console.log('First Name: ' + firstName + '\n' + 'Last Name: ' + lastName + '\n' + 'Age: ' + age + '\n' + 'Street: ' + street + '\n' + 'City: '+ city + '\n' + 'Zip Code: ' + zipCode );

//Line 9 (var city declaration and initialization) did not contain a quotation mark at the end of the string literal "some random city name". Quotation mark added.

//Line 15 (console.log function) contained a comma instead of a period between the class "console" and the method "log" instead of the expected period. Comma replaced with period
